### ISSUE TITLE
data files of chapter 7

### ISSUE THREAD

**Issue by mukoedo1993** [PacktPublishing/Hands-On-Machine-Learning-with-CPP#1]
Hello!
Where could I find data files of chapter 7?
Thanks,
mukoedo1993

**Comment by Kolkir** [comment]
Hi,
Please take them from the chapter 4.

Best regards,
Kirill Kolodiazhnyi.


12 мая 2021, 13:02:04, от mukoedo1993 ***@***.***>:



Hello!
Where could I find data files of chapter 7?
Thanks,
mukoedo1993

**Comment by mukoedo1993** [comment]
Thank you.
But, when I used data of chapter 4 to run chapter 7's SharkML program, I got segmentation fault.
Could you tell me how to do so? 
Thanks.

**Comment by Kolkir** [comment]
Am I understand right that other programs from chapter 7 work correctly with data files from chapter 4? If so please check that you use exact same version of SharkML library as book requires(built from source). Also a stack trace can help a lot.

**Comment by mukoedo1993** [comment]
I have changed my code to follow your CMakeLists.txt file strictly. Now, all problem have been solved. Thanks.
