### ISSUE TITLE
Running Code

### ISSUE THREAD

**Issue by trewise** [PacktPublishing/Hands-On-Machine-Learning-with-CPP#9]
I'm attempting to run the code examples in Visual Studio. What project type should I create? A cmake or console application? 

These files don't contain vsproj files, so I can't directly open them as a solution. Please help.

**Comment by hoangtv2000** [comment]
Run scripts step by step in https://github.com/PacktPublishing/Hands-On-Machine-Learning-with-CPP/tree/master/env_scripts

**Comment by Kolkir** [comment]
Hello @trewise I'm sorry but the samples were created and tested only for the Linux environment. You can configure Docker container and then use  Visual Studio Code as IDE.

**Comment by trewise** [comment]
I was able to fix the program to run in VS, however, I used matplotc++
library rather than plotcpp.

The book is great.

Thank you 🙏🏽
